api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    enable_swagger_ui: false
    enable_re_doc: true
    title: 'Symfony 5 + API Platform'
    description: 'An awesome API built with Symfony 5, PHP 7.4 and API Platform!'
    version: 1.0
    show_webby: false
